// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: ai-copilot/v1/ai-copilot.proto

package aicopilotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AICopilotService_Complete_FullMethodName = "/ai_copilot.v1.AICopilotService/Complete"
)

// AICopilotServiceClient is the client API for AICopilotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AICopilotServiceClient interface {
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
}

type aICopilotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAICopilotServiceClient(cc grpc.ClientConnInterface) AICopilotServiceClient {
	return &aICopilotServiceClient{cc}
}

func (c *aICopilotServiceClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, AICopilotService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AICopilotServiceServer is the server API for AICopilotService service.
// All implementations must embed UnimplementedAICopilotServiceServer
// for forward compatibility.
type AICopilotServiceServer interface {
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	mustEmbedUnimplementedAICopilotServiceServer()
}

// UnimplementedAICopilotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAICopilotServiceServer struct{}

func (UnimplementedAICopilotServiceServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedAICopilotServiceServer) mustEmbedUnimplementedAICopilotServiceServer() {}
func (UnimplementedAICopilotServiceServer) testEmbeddedByValue()                          {}

// UnsafeAICopilotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AICopilotServiceServer will
// result in compilation errors.
type UnsafeAICopilotServiceServer interface {
	mustEmbedUnimplementedAICopilotServiceServer()
}

func RegisterAICopilotServiceServer(s grpc.ServiceRegistrar, srv AICopilotServiceServer) {
	// If the following call pancis, it indicates UnimplementedAICopilotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AICopilotService_ServiceDesc, srv)
}

func _AICopilotService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AICopilotServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AICopilotService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AICopilotServiceServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AICopilotService_ServiceDesc is the grpc.ServiceDesc for AICopilotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AICopilotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_copilot.v1.AICopilotService",
	HandlerType: (*AICopilotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _AICopilotService_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai-copilot/v1/ai-copilot.proto",
}
