// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ai-copilot/v1/ai-copilot.proto

package aicopilotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	FileContent   string                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	CursorOffset  int32                  `protobuf:"varint,3,opt,name=cursor_offset,json=cursorOffset,proto3" json:"cursor_offset,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Temperature   float64                `protobuf:"fixed64,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Model         string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	ApiKey        string                 `protobuf:"bytes,8,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,9,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_ai_copilot_v1_ai_copilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_copilot_v1_ai_copilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_ai_copilot_v1_ai_copilot_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CompleteRequest) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *CompleteRequest) GetCursorOffset() int32 {
	if x != nil {
		return x.CursorOffset
	}
	return 0
}

func (x *CompleteRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CompleteRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompleteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CompleteRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestion    string                 `protobuf:"bytes,1,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_ai_copilot_v1_ai_copilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_copilot_v1_ai_copilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_ai_copilot_v1_ai_copilot_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

var File_ai_copilot_v1_ai_copilot_proto protoreflect.FileDescriptor

const file_ai_copilot_v1_ai_copilot_proto_rawDesc = "" +
	"\n" +
	"\x1eai-copilot/v1/ai-copilot.proto\x12\rai_copilot.v1\"\x9d\x02\n" +
	"\x0fCompleteRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12!\n" +
	"\ffile_content\x18\x02 \x01(\tR\vfileContent\x12#\n" +
	"\rcursor_offset\x18\x03 \x01(\x05R\fcursorOffset\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x17\n" +
	"\aapi_key\x18\b \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\t \x01(\tR\abaseUrl\"2\n" +
	"\x10CompleteResponse\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x01 \x01(\tR\n" +
	"suggestion2_\n" +
	"\x10AICopilotService\x12K\n" +
	"\bComplete\x12\x1e.ai_copilot.v1.CompleteRequest\x1a\x1f.ai_copilot.v1.CompleteResponseBDZBgithub.com/turmwerk/qeedu/backend/pkg/pb/ai-copilot/v1;aicopilotv1b\x06proto3"

var (
	file_ai_copilot_v1_ai_copilot_proto_rawDescOnce sync.Once
	file_ai_copilot_v1_ai_copilot_proto_rawDescData []byte
)

func file_ai_copilot_v1_ai_copilot_proto_rawDescGZIP() []byte {
	file_ai_copilot_v1_ai_copilot_proto_rawDescOnce.Do(func() {
		file_ai_copilot_v1_ai_copilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_copilot_v1_ai_copilot_proto_rawDesc), len(file_ai_copilot_v1_ai_copilot_proto_rawDesc)))
	})
	return file_ai_copilot_v1_ai_copilot_proto_rawDescData
}

var file_ai_copilot_v1_ai_copilot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_copilot_v1_ai_copilot_proto_goTypes = []any{
	(*CompleteRequest)(nil),  // 0: ai_copilot.v1.CompleteRequest
	(*CompleteResponse)(nil), // 1: ai_copilot.v1.CompleteResponse
}
var file_ai_copilot_v1_ai_copilot_proto_depIdxs = []int32{
	0, // 0: ai_copilot.v1.AICopilotService.Complete:input_type -> ai_copilot.v1.CompleteRequest
	1, // 1: ai_copilot.v1.AICopilotService.Complete:output_type -> ai_copilot.v1.CompleteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_copilot_v1_ai_copilot_proto_init() }
func file_ai_copilot_v1_ai_copilot_proto_init() {
	if File_ai_copilot_v1_ai_copilot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_copilot_v1_ai_copilot_proto_rawDesc), len(file_ai_copilot_v1_ai_copilot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_copilot_v1_ai_copilot_proto_goTypes,
		DependencyIndexes: file_ai_copilot_v1_ai_copilot_proto_depIdxs,
		MessageInfos:      file_ai_copilot_v1_ai_copilot_proto_msgTypes,
	}.Build()
	File_ai_copilot_v1_ai_copilot_proto = out.File
	file_ai_copilot_v1_ai_copilot_proto_goTypes = nil
	file_ai_copilot_v1_ai_copilot_proto_depIdxs = nil
}
