// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sandbox/v1/lsp.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnosticSeverity int32

const (
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_UNSPECIFIED DiagnosticSeverity = 0
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_ERROR       DiagnosticSeverity = 1
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_WARNING     DiagnosticSeverity = 2
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_INFORMATION DiagnosticSeverity = 3
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_HINT        DiagnosticSeverity = 4
)

// Enum value maps for DiagnosticSeverity.
var (
	DiagnosticSeverity_name = map[int32]string{
		0: "DIAGNOSTIC_SEVERITY_UNSPECIFIED",
		1: "DIAGNOSTIC_SEVERITY_ERROR",
		2: "DIAGNOSTIC_SEVERITY_WARNING",
		3: "DIAGNOSTIC_SEVERITY_INFORMATION",
		4: "DIAGNOSTIC_SEVERITY_HINT",
	}
	DiagnosticSeverity_value = map[string]int32{
		"DIAGNOSTIC_SEVERITY_UNSPECIFIED": 0,
		"DIAGNOSTIC_SEVERITY_ERROR":       1,
		"DIAGNOSTIC_SEVERITY_WARNING":     2,
		"DIAGNOSTIC_SEVERITY_INFORMATION": 3,
		"DIAGNOSTIC_SEVERITY_HINT":        4,
	}
)

func (x DiagnosticSeverity) Enum() *DiagnosticSeverity {
	p := new(DiagnosticSeverity)
	*p = x
	return p
}

func (x DiagnosticSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_lsp_proto_enumTypes[0].Descriptor()
}

func (DiagnosticSeverity) Type() protoreflect.EnumType {
	return &file_sandbox_v1_lsp_proto_enumTypes[0]
}

func (x DiagnosticSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticSeverity.Descriptor instead.
func (DiagnosticSeverity) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{0}
}

type WorkspaceFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceFile) Reset() {
	*x = WorkspaceFile{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceFile) ProtoMessage() {}

func (x *WorkspaceFile) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceFile.ProtoReflect.Descriptor instead.
func (*WorkspaceFile) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WorkspaceFile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type EnsureSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       uint64                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkspaceKey  string                 `protobuf:"bytes,2,opt,name=workspace_key,json=workspaceKey,proto3" json:"workspace_key,omitempty"`
	LanguageGroup string                 `protobuf:"bytes,3,opt,name=language_group,json=languageGroup,proto3" json:"language_group,omitempty"`
	Files         []*WorkspaceFile       `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureSessionRequest) Reset() {
	*x = EnsureSessionRequest{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionRequest) ProtoMessage() {}

func (x *EnsureSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionRequest.ProtoReflect.Descriptor instead.
func (*EnsureSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureSessionRequest) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *EnsureSessionRequest) GetWorkspaceKey() string {
	if x != nil {
		return x.WorkspaceKey
	}
	return ""
}

func (x *EnsureSessionRequest) GetLanguageGroup() string {
	if x != nil {
		return x.LanguageGroup
	}
	return ""
}

func (x *EnsureSessionRequest) GetFiles() []*WorkspaceFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type EnsureSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureSessionResponse) Reset() {
	*x = EnsureSessionResponse{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionResponse) ProtoMessage() {}

func (x *EnsureSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionResponse.ProtoReflect.Descriptor instead.
func (*EnsureSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SyncFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFileRequest) Reset() {
	*x = SyncFileRequest{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFileRequest) ProtoMessage() {}

func (x *SyncFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFileRequest.ProtoReflect.Descriptor instead.
func (*SyncFileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{3}
}

func (x *SyncFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyncFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SyncFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SyncFileRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SyncFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFileResponse) Reset() {
	*x = SyncFileResponse{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFileResponse) ProtoMessage() {}

func (x *SyncFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFileResponse.ProtoReflect.Descriptor instead.
func (*SyncFileResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{4}
}

type GetDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsRequest) Reset() {
	*x = GetDiagnosticsRequest{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsRequest) ProtoMessage() {}

func (x *GetDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{5}
}

func (x *GetDiagnosticsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartLine     int32                  `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartColumn   int32                  `protobuf:"varint,3,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	EndLine       int32                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndColumn     int32                  `protobuf:"varint,5,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	Severity      DiagnosticSeverity     `protobuf:"varint,6,opt,name=severity,proto3,enum=sandbox.v1.DiagnosticSeverity" json:"severity,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,9,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{6}
}

func (x *Diagnostic) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Diagnostic) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Diagnostic) GetStartColumn() int32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *Diagnostic) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Diagnostic) GetEndColumn() int32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

func (x *Diagnostic) GetSeverity() DiagnosticSeverity {
	if x != nil {
		return x.Severity
	}
	return DiagnosticSeverity_DIAGNOSTIC_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetDiagnosticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagnosticsResponse) Reset() {
	*x = GetDiagnosticsResponse{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagnosticsResponse) ProtoMessage() {}

func (x *GetDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*GetDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiagnosticsResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type GetCompletionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionsRequest) Reset() {
	*x = GetCompletionsRequest{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionsRequest) ProtoMessage() {}

func (x *GetCompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionsRequest.ProtoReflect.Descriptor instead.
func (*GetCompletionsRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{8}
}

func (x *GetCompletionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetCompletionsRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetCompletionsRequest) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *GetCompletionsRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *GetCompletionsRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CompletionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	InsertText    string                 `protobuf:"bytes,2,opt,name=insert_text,json=insertText,proto3" json:"insert_text,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Documentation string                 `protobuf:"bytes,4,opt,name=documentation,proto3" json:"documentation,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionItem) Reset() {
	*x = CompletionItem{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionItem) ProtoMessage() {}

func (x *CompletionItem) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionItem.ProtoReflect.Descriptor instead.
func (*CompletionItem) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{9}
}

func (x *CompletionItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CompletionItem) GetInsertText() string {
	if x != nil {
		return x.InsertText
	}
	return ""
}

func (x *CompletionItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CompletionItem) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *CompletionItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetCompletionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CompletionItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionsResponse) Reset() {
	*x = GetCompletionsResponse{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionsResponse) ProtoMessage() {}

func (x *GetCompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionsResponse.ProtoReflect.Descriptor instead.
func (*GetCompletionsResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{10}
}

func (x *GetCompletionsResponse) GetItems() []*CompletionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DestroyLSPSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyLSPSessionRequest) Reset() {
	*x = DestroyLSPSessionRequest{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyLSPSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyLSPSessionRequest) ProtoMessage() {}

func (x *DestroyLSPSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyLSPSessionRequest.ProtoReflect.Descriptor instead.
func (*DestroyLSPSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyLSPSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroyLSPSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyLSPSessionResponse) Reset() {
	*x = DestroyLSPSessionResponse{}
	mi := &file_sandbox_v1_lsp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyLSPSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyLSPSessionResponse) ProtoMessage() {}

func (x *DestroyLSPSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_lsp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyLSPSessionResponse.ProtoReflect.Descriptor instead.
func (*DestroyLSPSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_lsp_proto_rawDescGZIP(), []int{12}
}

var File_sandbox_v1_lsp_proto protoreflect.FileDescriptor

const file_sandbox_v1_lsp_proto_rawDesc = "" +
	"\n" +
	"\x14sandbox/v1/lsp.proto\x12\n" +
	"sandbox.v1\"Y\n" +
	"\rWorkspaceFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\xae\x01\n" +
	"\x14EnsureSessionRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x04R\aownerId\x12#\n" +
	"\rworkspace_key\x18\x02 \x01(\tR\fworkspaceKey\x12%\n" +
	"\x0elanguage_group\x18\x03 \x01(\tR\rlanguageGroup\x12/\n" +
	"\x05files\x18\x04 \x03(\v2\x19.sandbox.v1.WorkspaceFileR\x05files\"6\n" +
	"\x15EnsureSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x81\x01\n" +
	"\x0fSyncFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"\x12\n" +
	"\x10SyncFileResponse\"6\n" +
	"\x15GetDiagnosticsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa7\x02\n" +
	"\n" +
	"Diagnostic\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\x05R\tstartLine\x12!\n" +
	"\fstart_column\x18\x03 \x01(\x05R\vstartColumn\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x05R\aendLine\x12\x1d\n" +
	"\n" +
	"end_column\x18\x05 \x01(\x05R\tendColumn\x12:\n" +
	"\bseverity\x18\x06 \x01(\x0e2\x1e.sandbox.v1.DiagnosticSeverityR\bseverity\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\t \x01(\tR\x04code\"R\n" +
	"\x16GetDiagnosticsResponse\x128\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x16.sandbox.v1.DiagnosticR\vdiagnostics\"\x99\x01\n" +
	"\x15GetCompletionsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"\x99\x01\n" +
	"\x0eCompletionItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1f\n" +
	"\vinsert_text\x18\x02 \x01(\tR\n" +
	"insertText\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12$\n" +
	"\rdocumentation\x18\x04 \x01(\tR\rdocumentation\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"J\n" +
	"\x16GetCompletionsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.sandbox.v1.CompletionItemR\x05items\"9\n" +
	"\x18DestroyLSPSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x1b\n" +
	"\x19DestroyLSPSessionResponse*\xbc\x01\n" +
	"\x12DiagnosticSeverity\x12#\n" +
	"\x1fDIAGNOSTIC_SEVERITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DIAGNOSTIC_SEVERITY_ERROR\x10\x01\x12\x1f\n" +
	"\x1bDIAGNOSTIC_SEVERITY_WARNING\x10\x02\x12#\n" +
	"\x1fDIAGNOSTIC_SEVERITY_INFORMATION\x10\x03\x12\x1c\n" +
	"\x18DIAGNOSTIC_SEVERITY_HINT\x10\x042\xba\x03\n" +
	"\n" +
	"LSPService\x12T\n" +
	"\rEnsureSession\x12 .sandbox.v1.EnsureSessionRequest\x1a!.sandbox.v1.EnsureSessionResponse\x12E\n" +
	"\bSyncFile\x12\x1b.sandbox.v1.SyncFileRequest\x1a\x1c.sandbox.v1.SyncFileResponse\x12W\n" +
	"\x0eGetDiagnostics\x12!.sandbox.v1.GetDiagnosticsRequest\x1a\".sandbox.v1.GetDiagnosticsResponse\x12W\n" +
	"\x0eGetCompletions\x12!.sandbox.v1.GetCompletionsRequest\x1a\".sandbox.v1.GetCompletionsResponse\x12]\n" +
	"\x0eDestroySession\x12$.sandbox.v1.DestroyLSPSessionRequest\x1a%.sandbox.v1.DestroyLSPSessionResponseB?Z=github.com/turmwerk/qeedu/backend/pkg/pb/sandbox/v1;sandboxv1b\x06proto3"

var (
	file_sandbox_v1_lsp_proto_rawDescOnce sync.Once
	file_sandbox_v1_lsp_proto_rawDescData []byte
)

func file_sandbox_v1_lsp_proto_rawDescGZIP() []byte {
	file_sandbox_v1_lsp_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_lsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_lsp_proto_rawDesc), len(file_sandbox_v1_lsp_proto_rawDesc)))
	})
	return file_sandbox_v1_lsp_proto_rawDescData
}

var file_sandbox_v1_lsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandbox_v1_lsp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_sandbox_v1_lsp_proto_goTypes = []any{
	(DiagnosticSeverity)(0),           // 0: sandbox.v1.DiagnosticSeverity
	(*WorkspaceFile)(nil),             // 1: sandbox.v1.WorkspaceFile
	(*EnsureSessionRequest)(nil),      // 2: sandbox.v1.EnsureSessionRequest
	(*EnsureSessionResponse)(nil),     // 3: sandbox.v1.EnsureSessionResponse
	(*SyncFileRequest)(nil),           // 4: sandbox.v1.SyncFileRequest
	(*SyncFileResponse)(nil),          // 5: sandbox.v1.SyncFileResponse
	(*GetDiagnosticsRequest)(nil),     // 6: sandbox.v1.GetDiagnosticsRequest
	(*Diagnostic)(nil),                // 7: sandbox.v1.Diagnostic
	(*GetDiagnosticsResponse)(nil),    // 8: sandbox.v1.GetDiagnosticsResponse
	(*GetCompletionsRequest)(nil),     // 9: sandbox.v1.GetCompletionsRequest
	(*CompletionItem)(nil),            // 10: sandbox.v1.CompletionItem
	(*GetCompletionsResponse)(nil),    // 11: sandbox.v1.GetCompletionsResponse
	(*DestroyLSPSessionRequest)(nil),  // 12: sandbox.v1.DestroyLSPSessionRequest
	(*DestroyLSPSessionResponse)(nil), // 13: sandbox.v1.DestroyLSPSessionResponse
}
var file_sandbox_v1_lsp_proto_depIdxs = []int32{
	1,  // 0: sandbox.v1.EnsureSessionRequest.files:type_name -> sandbox.v1.WorkspaceFile
	0,  // 1: sandbox.v1.Diagnostic.severity:type_name -> sandbox.v1.DiagnosticSeverity
	7,  // 2: sandbox.v1.GetDiagnosticsResponse.diagnostics:type_name -> sandbox.v1.Diagnostic
	10, // 3: sandbox.v1.GetCompletionsResponse.items:type_name -> sandbox.v1.CompletionItem
	2,  // 4: sandbox.v1.LSPService.EnsureSession:input_type -> sandbox.v1.EnsureSessionRequest
	4,  // 5: sandbox.v1.LSPService.SyncFile:input_type -> sandbox.v1.SyncFileRequest
	6,  // 6: sandbox.v1.LSPService.GetDiagnostics:input_type -> sandbox.v1.GetDiagnosticsRequest
	9,  // 7: sandbox.v1.LSPService.GetCompletions:input_type -> sandbox.v1.GetCompletionsRequest
	12, // 8: sandbox.v1.LSPService.DestroySession:input_type -> sandbox.v1.DestroyLSPSessionRequest
	3,  // 9: sandbox.v1.LSPService.EnsureSession:output_type -> sandbox.v1.EnsureSessionResponse
	5,  // 10: sandbox.v1.LSPService.SyncFile:output_type -> sandbox.v1.SyncFileResponse
	8,  // 11: sandbox.v1.LSPService.GetDiagnostics:output_type -> sandbox.v1.GetDiagnosticsResponse
	11, // 12: sandbox.v1.LSPService.GetCompletions:output_type -> sandbox.v1.GetCompletionsResponse
	13, // 13: sandbox.v1.LSPService.DestroySession:output_type -> sandbox.v1.DestroyLSPSessionResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sandbox_v1_lsp_proto_init() }
func file_sandbox_v1_lsp_proto_init() {
	if File_sandbox_v1_lsp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_lsp_proto_rawDesc), len(file_sandbox_v1_lsp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_lsp_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_lsp_proto_depIdxs,
		EnumInfos:         file_sandbox_v1_lsp_proto_enumTypes,
		MessageInfos:      file_sandbox_v1_lsp_proto_msgTypes,
	}.Build()
	File_sandbox_v1_lsp_proto = out.File
	file_sandbox_v1_lsp_proto_goTypes = nil
	file_sandbox_v1_lsp_proto_depIdxs = nil
}
