// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: sandbox/v1/lsp.proto

package sandboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LSPServiceClient is the client API for LSPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LSPServiceClient interface {
	EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*EnsureSessionResponse, error)
	SyncFile(ctx context.Context, in *SyncFileRequest, opts ...grpc.CallOption) (*SyncFileResponse, error)
	GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*GetDiagnosticsResponse, error)
	GetCompletions(ctx context.Context, in *GetCompletionsRequest, opts ...grpc.CallOption) (*GetCompletionsResponse, error)
	DestroySession(ctx context.Context, in *DestroyLSPSessionRequest, opts ...grpc.CallOption) (*DestroyLSPSessionResponse, error)
}

type lSPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLSPServiceClient(cc grpc.ClientConnInterface) LSPServiceClient {
	return &lSPServiceClient{cc}
}

func (c *lSPServiceClient) EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*EnsureSessionResponse, error) {
	out := new(EnsureSessionResponse)
	err := c.cc.Invoke(ctx, "/sandbox.v1.LSPService/EnsureSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lSPServiceClient) SyncFile(ctx context.Context, in *SyncFileRequest, opts ...grpc.CallOption) (*SyncFileResponse, error) {
	out := new(SyncFileResponse)
	err := c.cc.Invoke(ctx, "/sandbox.v1.LSPService/SyncFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lSPServiceClient) GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*GetDiagnosticsResponse, error) {
	out := new(GetDiagnosticsResponse)
	err := c.cc.Invoke(ctx, "/sandbox.v1.LSPService/GetDiagnostics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lSPServiceClient) GetCompletions(ctx context.Context, in *GetCompletionsRequest, opts ...grpc.CallOption) (*GetCompletionsResponse, error) {
	out := new(GetCompletionsResponse)
	err := c.cc.Invoke(ctx, "/sandbox.v1.LSPService/GetCompletions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lSPServiceClient) DestroySession(ctx context.Context, in *DestroyLSPSessionRequest, opts ...grpc.CallOption) (*DestroyLSPSessionResponse, error) {
	out := new(DestroyLSPSessionResponse)
	err := c.cc.Invoke(ctx, "/sandbox.v1.LSPService/DestroySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LSPServiceServer is the server API for LSPService service.
// All implementations must embed UnimplementedLSPServiceServer
// for forward compatibility
type LSPServiceServer interface {
	EnsureSession(context.Context, *EnsureSessionRequest) (*EnsureSessionResponse, error)
	SyncFile(context.Context, *SyncFileRequest) (*SyncFileResponse, error)
	GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*GetDiagnosticsResponse, error)
	GetCompletions(context.Context, *GetCompletionsRequest) (*GetCompletionsResponse, error)
	DestroySession(context.Context, *DestroyLSPSessionRequest) (*DestroyLSPSessionResponse, error)
	mustEmbedUnimplementedLSPServiceServer()
}

// UnimplementedLSPServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLSPServiceServer struct {
}

func (UnimplementedLSPServiceServer) EnsureSession(context.Context, *EnsureSessionRequest) (*EnsureSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureSession not implemented")
}
func (UnimplementedLSPServiceServer) SyncFile(context.Context, *SyncFileRequest) (*SyncFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncFile not implemented")
}
func (UnimplementedLSPServiceServer) GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*GetDiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedLSPServiceServer) GetCompletions(context.Context, *GetCompletionsRequest) (*GetCompletionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompletions not implemented")
}
func (UnimplementedLSPServiceServer) DestroySession(context.Context, *DestroyLSPSessionRequest) (*DestroyLSPSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedLSPServiceServer) mustEmbedUnimplementedLSPServiceServer() {}

// UnsafeLSPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LSPServiceServer will
// result in compilation errors.
type UnsafeLSPServiceServer interface {
	mustEmbedUnimplementedLSPServiceServer()
}

func RegisterLSPServiceServer(s grpc.ServiceRegistrar, srv LSPServiceServer) {
	s.RegisterService(&LSPService_ServiceDesc, srv)
}

func _LSPService_EnsureSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSPServiceServer).EnsureSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.v1.LSPService/EnsureSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSPServiceServer).EnsureSession(ctx, req.(*EnsureSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LSPService_SyncFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSPServiceServer).SyncFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.v1.LSPService/SyncFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSPServiceServer).SyncFile(ctx, req.(*SyncFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LSPService_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSPServiceServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.v1.LSPService/GetDiagnostics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSPServiceServer).GetDiagnostics(ctx, req.(*GetDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LSPService_GetCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompletionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSPServiceServer).GetCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.v1.LSPService/GetCompletions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSPServiceServer).GetCompletions(ctx, req.(*GetCompletionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LSPService_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyLSPSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LSPServiceServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.v1.LSPService/DestroySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LSPServiceServer).DestroySession(ctx, req.(*DestroyLSPSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LSPService_ServiceDesc is the grpc.ServiceDesc for LSPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LSPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.v1.LSPService",
	HandlerType: (*LSPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureSession",
			Handler:    _LSPService_EnsureSession_Handler,
		},
		{
			MethodName: "SyncFile",
			Handler:    _LSPService_SyncFile_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _LSPService_GetDiagnostics_Handler,
		},
		{
			MethodName: "GetCompletions",
			Handler:    _LSPService_GetCompletions_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _LSPService_DestroySession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox/v1/lsp.proto",
}
