// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sandbox/v1/runner.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Stdin          string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	mi := &file_sandbox_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RunCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunCodeRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *RunCodeRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RunCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExecutionMs   int64                  `protobuf:"varint,4,opt,name=execution_ms,json=executionMs,proto3" json:"execution_ms,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	mi := &file_sandbox_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RunCodeResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RunCodeResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *RunCodeResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunCodeResponse) GetExecutionMs() int64 {
	if x != nil {
		return x.ExecutionMs
	}
	return 0
}

func (x *RunCodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sandbox_v1_runner_proto protoreflect.FileDescriptor

const file_sandbox_v1_runner_proto_rawDesc = "" +
	"\n" +
	"\x17sandbox/v1/runner.proto\x12\n" +
	"sandbox.v1\"\x7f\n" +
	"\x0eRunCodeRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\x97\x01\n" +
	"\x0fRunCodeResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12!\n" +
	"\fexecution_ms\x18\x04 \x01(\x03R\vexecutionMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2S\n" +
	"\rRunnerService\x12B\n" +
	"\aRunCode\x12\x1a.sandbox.v1.RunCodeRequest\x1a\x1b.sandbox.v1.RunCodeResponseBLZJgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/sandbox/v1;sandboxv1b\x06proto3"

var (
	file_sandbox_v1_runner_proto_rawDescOnce sync.Once
	file_sandbox_v1_runner_proto_rawDescData []byte
)

func file_sandbox_v1_runner_proto_rawDescGZIP() []byte {
	file_sandbox_v1_runner_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_runner_proto_rawDesc), len(file_sandbox_v1_runner_proto_rawDesc)))
	})
	return file_sandbox_v1_runner_proto_rawDescData
}

var file_sandbox_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandbox_v1_runner_proto_goTypes = []any{
	(*RunCodeRequest)(nil),  // 0: sandbox.v1.RunCodeRequest
	(*RunCodeResponse)(nil), // 1: sandbox.v1.RunCodeResponse
}
var file_sandbox_v1_runner_proto_depIdxs = []int32{
	0, // 0: sandbox.v1.RunnerService.RunCode:input_type -> sandbox.v1.RunCodeRequest
	1, // 1: sandbox.v1.RunnerService.RunCode:output_type -> sandbox.v1.RunCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_v1_runner_proto_init() }
func file_sandbox_v1_runner_proto_init() {
	if File_sandbox_v1_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_runner_proto_rawDesc), len(file_sandbox_v1_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_runner_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_runner_proto_depIdxs,
		MessageInfos:      file_sandbox_v1_runner_proto_msgTypes,
	}.Build()
	File_sandbox_v1_runner_proto = out.File
	file_sandbox_v1_runner_proto_goTypes = nil
	file_sandbox_v1_runner_proto_depIdxs = nil
}
