// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sandbox/v1/terminal.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Shell          string                 `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *ExecuteCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteCommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shell         string                 `protobuf:"bytes,1,opt,name=shell,proto3" json:"shell,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *CreateSessionRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CreateSessionRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{4}
}

func (x *DestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{5}
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Resize        *ResizeEvent           `protobuf:"bytes,3,opt,name=resize,proto3" json:"resize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalInput) GetResize() *ResizeEvent {
	if x != nil {
		return x.Resize
	}
	return nil
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Closed        bool                   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{7}
}

func (x *TerminalOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalOutput) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type ResizeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeEvent) Reset() {
	*x = ResizeEvent{}
	mi := &file_sandbox_v1_terminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeEvent) ProtoMessage() {}

func (x *ResizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_terminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeEvent.ProtoReflect.Descriptor instead.
func (*ResizeEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_terminal_proto_rawDescGZIP(), []int{8}
}

func (x *ResizeEvent) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeEvent) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

var File_sandbox_v1_terminal_proto protoreflect.FileDescriptor

const file_sandbox_v1_terminal_proto_rawDesc = "" +
	"\n" +
	"\x19sandbox/v1/terminal.proto\x12\n" +
	"sandbox.v1\"\x91\x01\n" +
	"\x15ExecuteCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\"e\n" +
	"\x16ExecuteCommandResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"T\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05shell\x18\x01 \x01(\tR\x05shell\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x18\n" +
	"\x16DestroySessionResponse\"s\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12/\n" +
	"\x06resize\x18\x03 \x01(\v2\x17.sandbox.v1.ResizeEventR\x06resize\"[\n" +
	"\x0eTerminalOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed\"5\n" +
	"\vResizeEvent\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows2\xea\x02\n" +
	"\x0fTerminalService\x12W\n" +
	"\x0eExecuteCommand\x12!.sandbox.v1.ExecuteCommandRequest\x1a\".sandbox.v1.ExecuteCommandResponse\x12T\n" +
	"\rCreateSession\x12 .sandbox.v1.CreateSessionRequest\x1a!.sandbox.v1.CreateSessionResponse\x12W\n" +
	"\x0eDestroySession\x12!.sandbox.v1.DestroySessionRequest\x1a\".sandbox.v1.DestroySessionResponse\x12O\n" +
	"\x12InteractiveSession\x12\x19.sandbox.v1.TerminalInput\x1a\x1a.sandbox.v1.TerminalOutput(\x010\x01B?Z=github.com/turmwerk/qeedu/backend/pkg/pb/sandbox/v1;sandboxv1b\x06proto3"

var (
	file_sandbox_v1_terminal_proto_rawDescOnce sync.Once
	file_sandbox_v1_terminal_proto_rawDescData []byte
)

func file_sandbox_v1_terminal_proto_rawDescGZIP() []byte {
	file_sandbox_v1_terminal_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_terminal_proto_rawDesc), len(file_sandbox_v1_terminal_proto_rawDesc)))
	})
	return file_sandbox_v1_terminal_proto_rawDescData
}

var file_sandbox_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sandbox_v1_terminal_proto_goTypes = []any{
	(*ExecuteCommandRequest)(nil),  // 0: sandbox.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil), // 1: sandbox.v1.ExecuteCommandResponse
	(*CreateSessionRequest)(nil),   // 2: sandbox.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 3: sandbox.v1.CreateSessionResponse
	(*DestroySessionRequest)(nil),  // 4: sandbox.v1.DestroySessionRequest
	(*DestroySessionResponse)(nil), // 5: sandbox.v1.DestroySessionResponse
	(*TerminalInput)(nil),          // 6: sandbox.v1.TerminalInput
	(*TerminalOutput)(nil),         // 7: sandbox.v1.TerminalOutput
	(*ResizeEvent)(nil),            // 8: sandbox.v1.ResizeEvent
}
var file_sandbox_v1_terminal_proto_depIdxs = []int32{
	8, // 0: sandbox.v1.TerminalInput.resize:type_name -> sandbox.v1.ResizeEvent
	0, // 1: sandbox.v1.TerminalService.ExecuteCommand:input_type -> sandbox.v1.ExecuteCommandRequest
	2, // 2: sandbox.v1.TerminalService.CreateSession:input_type -> sandbox.v1.CreateSessionRequest
	4, // 3: sandbox.v1.TerminalService.DestroySession:input_type -> sandbox.v1.DestroySessionRequest
	6, // 4: sandbox.v1.TerminalService.InteractiveSession:input_type -> sandbox.v1.TerminalInput
	1, // 5: sandbox.v1.TerminalService.ExecuteCommand:output_type -> sandbox.v1.ExecuteCommandResponse
	3, // 6: sandbox.v1.TerminalService.CreateSession:output_type -> sandbox.v1.CreateSessionResponse
	5, // 7: sandbox.v1.TerminalService.DestroySession:output_type -> sandbox.v1.DestroySessionResponse
	7, // 8: sandbox.v1.TerminalService.InteractiveSession:output_type -> sandbox.v1.TerminalOutput
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sandbox_v1_terminal_proto_init() }
func file_sandbox_v1_terminal_proto_init() {
	if File_sandbox_v1_terminal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_terminal_proto_rawDesc), len(file_sandbox_v1_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_terminal_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_terminal_proto_depIdxs,
		MessageInfos:      file_sandbox_v1_terminal_proto_msgTypes,
	}.Build()
	File_sandbox_v1_terminal_proto = out.File
	file_sandbox_v1_terminal_proto_goTypes = nil
	file_sandbox_v1_terminal_proto_depIdxs = nil
}
