# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes for AIChatService."""
import grpc
from app.rpc import ai_chat_pb2 as ai__chat__pb2


class AIChatServiceStub(object):
    """Client stub for AIChatService."""
    def __init__(self, channel):
        self.Chat = channel.unary_stream(
            '/ai_chat.v1.AIChatService/Chat',
            request_serializer=ai__chat__pb2.ChatRequest.SerializeToString,
            response_deserializer=ai__chat__pb2.ChatResponse.FromString,
        )
        self.FixBug = channel.unary_stream(
            '/ai_chat.v1.AIChatService/FixBug',
            request_serializer=ai__chat__pb2.FixBugRequest.SerializeToString,
            response_deserializer=ai__chat__pb2.FixBugResponse.FromString,
        )


class AIChatServiceServicer(object):
    """Server interface for AIChatService."""
    def Chat(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FixBug(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIChatServiceServicer_to_server(servicer, server):
    from grpc import unary_stream_rpc_method_handler
    rpc_method_handlers = {
        'Chat': unary_stream_rpc_method_handler(
            servicer.Chat,
            request_deserializer=ai__chat__pb2.ChatRequest.FromString,
            response_serializer=ai__chat__pb2.ChatResponse.SerializeToString,
        ),
        'FixBug': unary_stream_rpc_method_handler(
            servicer.FixBug,
            request_deserializer=ai__chat__pb2.FixBugRequest.FromString,
            response_serializer=ai__chat__pb2.FixBugResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_service_handler('ai_chat.v1.AIChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
