# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, '', 'ai-chat/v1/ai-chat.proto'
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x61i-chat/v1/ai-chat.proto\x12\nai_chat.v1'
    b'\"9\n\x0b\x43hatMessage\x12\x12\n\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n\x07\x63ontent\x18\x02 \x01(\tR\x07\x63ontent'
    b'\"w\n\x0b\x43hatRequest\x12\x31\n\x08messages\x18\x01 \x03(\x0b\x32\x17.ai_chat.v1.ChatMessageR\x08messages'
    b'\x12!\n\x0c\x66ile_context\x18\x02 \x01(\tR\x0b\x66ileContext'
    b'\x12\x12\n\x08language\x18\x03 \x01(\tR\x08language'
    b'\"8\n\x0c\x43hatResponse\x12\x14\n\x05\x64\x65lta\x18\x01 \x01(\tR\x05\x64\x65lta\x12\x12\n\x04\x64one\x18\x02 \x01(\x08R\x04\x64one'
    b'\"_\n\rFixBugRequest\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode'
    b'\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage'
    b'\x12\x15\n\x08language\x18\x03 \x01(\tR\x08language'
    b'\":\n\x0e\x46ixBugResponse\x12\x14\n\x05\x64\x65lta\x18\x01 \x01(\tR\x05\x64\x65lta\x12\x12\n\x04\x64one\x18\x02 \x01(\x08R\x04\x64one'
    b'\x32\x93\x01\n\rAIChatService'
    b'\x12?\n\x04\x43hat\x12\x17.ai_chat.v1.ChatRequest\x1a\x18.ai_chat.v1.ChatResponse\"\x00\x30\x01'
    b'\x12\x41\n\x06\x46ixBug\x12\x19.ai_chat.v1.FixBugRequest\x1a\x1a.ai_chat.v1.FixBugResponse\x30\x01'
    b'BOZMgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-chat/v1;aichatv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-chat/v1;aichatv1'
