import React from "react";
import type { Feature } from "@/feature/ModuleHub";
import {
  BankOutlinedIcon,
  DeploymentUnitOutlinedIcon,
  EnvironmentOutlinedIcon,
  GlobalOutlinedIcon,
  MailOutlinedIcon,
  RocketOutlinedIcon,
  RollbackOutlinedIcon,
  SafetyOutlinedIcon,
  SearchOutlinedIcon,
  TranslationOutlinedIcon,
} from "@/ui/Icon";

type ModuleCatalogEntry = {
  key: string;
  title: string;
  shortLabel: string;
  desc: string;
  to: string;
  icon: React.ReactNode;
  badgeLabel: string;
  footerLabel: string;
  subLinks: Feature["subLinks"];
  landingHeadline: string;
  landingSubtitle: string;
  landingFeatures: Feature[];
};

const entry = (
  value: ModuleCatalogEntry,
): ModuleCatalogEntry => value;

export const internationalModuleCatalog: ModuleCatalogEntry[] = [
  entry({
    key: "international-exchange-hub",
    title: "交换与访学项目中心",
    shortLabel: "项目中心",
    desc: "集中查看 partner universities、交换、暑校、短期访学与联合培养项目。",
    to: "/international/exchange-hub",
    icon: <GlobalOutlinedIcon />,
    badgeLabel: "Projects",
    footerLabel: "项目总入口",
    subLinks: [
      { label: "项目清单", to: "/international/exchange-hub/ListPage" },
      { label: "申请决策", to: "/international/matching-lab" },
      { label: "流程安排", to: "/international/process-flow" },
    ],
    landingHeadline: "交换与访学项目中心",
    landingSubtitle: "从合作院校筛选、项目门槛比较到正式纳入申请池，都在这里完成。",
    landingFeatures: [
      {
        key: "exchange-directory",
        title: "合作院校总目录",
        desc: "按地区、院校、学期和项目类型筛出可申请条目，沉淀统一项目库。",
        to: "/international/exchange-hub/ListPage",
        icon: <BankOutlinedIcon />,
        badgeLabel: "Directory",
        footerLabel: "院校与项目池",
      },
      {
        key: "exchange-criteria",
        title: "申请门槛与名额比较",
        desc: "对齐 GPA、语言、预算、学分要求和名额限制，提前识别硬门槛。",
        to: "/international/matching-lab",
        icon: <SearchOutlinedIcon />,
        badgeLabel: "Criteria",
        footerLabel: "门槛与比较",
      },
      {
        key: "exchange-timeline",
        title: "学期节奏与节点排程",
        desc: "把官网 deadline、校内审批、提名与递交流程对齐成统一时间线。",
        to: "/international/process-flow",
        icon: <DeploymentUnitOutlinedIcon />,
        badgeLabel: "Timeline",
        footerLabel: "申请时间节奏",
      },
      {
        key: "exchange-briefing",
        title: "项目摘要与决策纪要",
        desc: "为每个候选项目生成可比摘要，方便和老师、家长或导师快速讨论。",
        to: "/international/exchange-hub/ListPage",
        icon: <MailOutlinedIcon />,
        badgeLabel: "Brief",
        footerLabel: "方案讨论材料",
      },
    ],
  }),
  entry({
    key: "international-matching-lab",
    title: "智能项目匹配与申请决策",
    shortLabel: "项目匹配",
    desc: "根据 GPA、语言、预算、国家和时间安排推荐合适项目，并支持多项目比较。",
    to: "/international/matching-lab",
    icon: <SearchOutlinedIcon />,
    badgeLabel: "Matching",
    footerLabel: "匹配与比较",
    subLinks: [
      { label: "候选推荐", to: "/international/matching-lab/ListPage" },
      { label: "项目中心", to: "/international/exchange-hub" },
      { label: "邮件沟通", to: "/international/writing-desk" },
    ],
    landingHeadline: "智能项目匹配与申请决策",
    landingSubtitle: "把个人画像、项目门槛和风险偏好放到同一个决策面板里，输出真正可执行的候选名单。",
    landingFeatures: [
      {
        key: "matching-profile",
        title: "个人画像与约束建模",
        desc: "录入 GPA、语言、预算、国家偏好、时长与课程诉求，形成可计算的申请画像。",
        to: "/international/matching-lab/ListPage",
        icon: <SearchOutlinedIcon />,
        badgeLabel: "Profile",
        footerLabel: "申请人画像",
      },
      {
        key: "matching-compare",
        title: "多项目打分与对比",
        desc: "从门槛适配、课程匹配、预算压力和时间可行性四个维度做候选比较。",
        to: "/international/exchange-hub/ListPage",
        icon: <BankOutlinedIcon />,
        badgeLabel: "Compare",
        footerLabel: "候选集筛选",
      },
      {
        key: "matching-decision",
        title: "申报优先级与备选策略",
        desc: "生成冲刺、稳妥、保底三层清单，避免把所有精力压在单一项目上。",
        to: "/international/matching-lab/ListPage",
        icon: <DeploymentUnitOutlinedIcon />,
        badgeLabel: "Decision",
        footerLabel: "优先级排序",
      },
      {
        key: "matching-material",
        title: "申报依据与说明稿",
        desc: "自动沉淀推荐理由、比较结论和沟通要点，方便后续写邮件或做说明。",
        to: "/international/writing-desk",
        icon: <MailOutlinedIcon />,
        badgeLabel: "Output",
        footerLabel: "比较结论输出",
      },
    ],
  }),
  entry({
    key: "international-process-flow",
    title: "申请流程助手",
    shortLabel: "流程助手",
    desc: "自动生成个人 checklist 和申请时间线，跟踪报名、审批、材料与签证节点。",
    to: "/international/process-flow",
    icon: <DeploymentUnitOutlinedIcon />,
    badgeLabel: "Checklist",
    footerLabel: "流程管理",
    subLinks: [
      { label: "节点清单", to: "/international/process-flow/ListPage" },
      { label: "行前准备", to: "/international/pre-departure" },
      { label: "回国归档", to: "/international/return-service" },
    ],
    landingHeadline: "申请流程助手",
    landingSubtitle: "把校内审批、平台提交、签证和材料准备串成真正能执行的节点链，不再靠碎片备忘录推进。",
    landingFeatures: [
      {
        key: "process-checklist",
        title: "个人 Checklist 自动拆解",
        desc: "按角色、节点和截止时间生成待办，并把高风险节点单独标红。",
        to: "/international/process-flow/ListPage",
        icon: <DeploymentUnitOutlinedIcon />,
        badgeLabel: "Checklist",
        footerLabel: "节点总控",
      },
      {
        key: "process-approval",
        title: "校内审批与签字流转",
        desc: "沉淀学院、国际处、导师和平台的签字要求，减少来回返工。",
        to: "/international/process-flow/ListPage",
        icon: <BankOutlinedIcon />,
        badgeLabel: "Approval",
        footerLabel: "审批链梳理",
      },
      {
        key: "process-visa",
        title: "签证与官方材料跟踪",
        desc: "单独管理签证预约、保险、录取文件与入境材料，避免和校内流程混在一起。",
        to: "/international/pre-departure",
        icon: <RocketOutlinedIcon />,
        badgeLabel: "Visa",
        footerLabel: "证件与出入境",
      },
      {
        key: "process-risk",
        title: "堵点识别与补救动作",
        desc: "把缺材料、格式不符、系统失败等卡点改写为可执行的补救动作。",
        to: "/international/process-flow/ListPage",
        icon: <SafetyOutlinedIcon />,
        badgeLabel: "Risk",
        footerLabel: "风险处置",
      },
    ],
  }),
  entry({
    key: "international-writing-desk",
    title: "多语言沟通与邮件助手",
    shortLabel: "邮件助手",
    desc: "支持中英双语邮件、通知、FAQ、导师联系、签证说明与住宿沟通写作。",
    to: "/international/writing-desk",
    icon: <MailOutlinedIcon />,
    badgeLabel: "Communication",
    footerLabel: "写作与沟通",
    subLinks: [
      { label: "邮件草稿", to: "/international/writing-desk/ListPage" },
      { label: "项目匹配", to: "/international/matching-lab" },
      { label: "来华支持", to: "/international/welcome-portal" },
    ],
    landingHeadline: "多语言沟通与邮件助手",
    landingSubtitle: "不只是润色邮件，而是把导师联系、项目问询、签证说明、住宿沟通和 FAQ 都纳入统一沟通工作台。",
    landingFeatures: [
      {
        key: "email-first-contact",
        title: "导师与项目首次联系",
        desc: "生成首封问询邮件、项目咨询邮件和 follow-up 版本，控制语气与长度。",
        to: "/international/writing-desk/ListPage",
        icon: <MailOutlinedIcon />,
        badgeLabel: "Outreach",
        footerLabel: "首次联系邮件",
      },
      {
        key: "email-bilingual",
        title: "中英双语通知与 FAQ",
        desc: "把常见问题、办理须知、签证说明和住宿通知整理成双语版本。",
        to: "/international/writing-desk/ListPage",
        icon: <TranslationOutlinedIcon />,
        badgeLabel: "Bilingual",
        footerLabel: "通知与 FAQ",
      },
      {
        key: "email-proof",
        title: "附件说明与发送前检查",
        desc: "统一管理附件命名、链接说明、closing 语和发送前核对清单。",
        to: "/international/process-flow",
        icon: <DeploymentUnitOutlinedIcon />,
        badgeLabel: "Checklist",
        footerLabel: "发送前终检",
      },
      {
        key: "email-support",
        title: "住宿、签证与校务沟通",
        desc: "针对宿舍、保险、报到、课程变更等场景生成更稳妥的沟通草稿。",
        to: "/international/welcome-portal",
        icon: <GlobalOutlinedIcon />,
        badgeLabel: "Support",
        footerLabel: "事务沟通模板",
      },
    ],
  }),
  entry({
    key: "international-pre-departure",
    title: "行前准备助手",
    shortLabel: "行前准备",
    desc: "生成出发前任务清单，覆盖签证、保险、机票、住宿、注册与银行卡等事项。",
    to: "/international/pre-departure",
    icon: <RocketOutlinedIcon />,
    badgeLabel: "Departure",
    footerLabel: "出发前准备",
    subLinks: [
      { label: "证件清单", to: "/international/pre-departure/ListPage" },
      { label: "在外支持", to: "/international/abroad-life" },
      { label: "跨文化培训", to: "/international/cultural-training" },
    ],
    landingHeadline: "行前准备助手",
    landingSubtitle: "把签证、保险、住宿、交通、行李和落地首周安排拆成倒计时工作台，避免临出发前被动补漏。",
    landingFeatures: [
      {
        key: "departure-docs",
        title: "证件与签证核验",
        desc: "护照、签证、录取函、保险单和学校要求逐项核验，避免出境前翻车。",
        to: "/international/pre-departure/ListPage",
        icon: <RocketOutlinedIcon />,
        badgeLabel: "Docs",
        footerLabel: "证件与签证",
      },
      {
        key: "departure-housing",
        title: "住宿交通落地安排",
        desc: "确认首晚住宿、接机路线、入住宿舍和到校路径，衔接到达第一周安排。",
        to: "/international/abroad-life",
        icon: <EnvironmentOutlinedIcon />,
        badgeLabel: "Arrival",
        footerLabel: "落地安排",
      },
      {
        key: "departure-pack",
        title: "行李与应急包规划",
        desc: "按季节、药品、电器、学习用品和证件备份生成打包清单。",
        to: "/international/pre-departure/ListPage",
        icon: <MailOutlinedIcon />,
        badgeLabel: "Packing",
        footerLabel: "打包与备份",
      },
      {
        key: "departure-risk",
        title: "出境前风险提醒",
        desc: "同步当地法律、保险使用、时差、通讯和紧急联系卡等高风险信息。",
        to: "/international/cultural-training",
        icon: <SafetyOutlinedIcon />,
        badgeLabel: "Risk",
        footerLabel: "安全与应急",
      },
    ],
  }),
  entry({
    key: "international-cultural-training",
    title: "跨文化培训与风险提示",
    shortLabel: "跨文化培训",
    desc: "提供学术礼仪、课堂参与、学术诚信、当地法律、安全事项与应急提示。",
    to: "/international/cultural-training",
    icon: <TranslationOutlinedIcon />,
    badgeLabel: "Culture",
    footerLabel: "适应与安全",
    subLinks: [
      { label: "文化适应", to: "/international/cultural-training/ListPage" },
      { label: "在外支持", to: "/international/abroad-life" },
      { label: "回国沉淀", to: "/international/return-service" },
    ],
    landingHeadline: "跨文化培训与风险提示",
    landingSubtitle: "围绕课堂参与、学术表达、法律意识和安全预案做情境化提示，而不是只给一页抽象提醒。",
    landingFeatures: [
      {
        key: "culture-academic",
        title: "课堂参与与学术礼仪",
        desc: "整理课堂讨论、office hour、邮件礼仪和学术诚信等高频情境建议。",
        to: "/international/cultural-training/ListPage",
        icon: <TranslationOutlinedIcon />,
        badgeLabel: "Academic",
        footerLabel: "课堂与学术",
      },
      {
        key: "culture-law",
        title: "当地法律与制度提醒",
        desc: "聚合居留、兼职、医疗、交通和住宿合同等容易踩线的规则提示。",
        to: "/international/cultural-training/ListPage",
        icon: <SafetyOutlinedIcon />,
        badgeLabel: "Law",
        footerLabel: "规则与边界",
      },
      {
        key: "culture-safety",
        title: "安全场景与应急预案",
        desc: "针对夜间出行、证件遗失、医疗就诊和校园报警等场景给出具体动作。",
        to: "/international/abroad-life",
        icon: <EnvironmentOutlinedIcon />,
        badgeLabel: "Safety",
        footerLabel: "应急处置",
      },
      {
        key: "culture-reflection",
        title: "适应反馈与经验回流",
        desc: "把适应过程中的案例和建议沉淀下来，供后来者复用。",
        to: "/international/return-service",
        icon: <RollbackOutlinedIcon />,
        badgeLabel: "Reflection",
        footerLabel: "培训复盘",
      },
    ],
  }),
  entry({
    key: "international-abroad-life",
    title: "在外期间支持",
    shortLabel: "在外支持",
    desc: "提供选课调整、学分确认、住宿续约、签证续办和常见紧急事务支持。",
    to: "/international/abroad-life",
    icon: <EnvironmentOutlinedIcon />,
    badgeLabel: "Abroad",
    footerLabel: "在外服务",
    subLinks: [
      { label: "生活支持", to: "/international/abroad-life/ListPage" },
      { label: "风险提示", to: "/international/cultural-training" },
      { label: "回国事项", to: "/international/return-service" },
    ],
    landingHeadline: "在外期间支持",
    landingSubtitle: "在海外期间的课程、住宿、签证和突发事务支持统一放在一个场景化工作台里。",
    landingFeatures: [
      {
        key: "abroad-course",
        title: "选课调整与学分确认",
        desc: "跟踪课程替换、学院确认和学分认定前置材料，避免回国后补材料。",
        to: "/international/abroad-life/ListPage",
        icon: <BankOutlinedIcon />,
        badgeLabel: "Course",
        footerLabel: "课程与学分",
      },
      {
        key: "abroad-housing",
        title: "住宿续约与生活问题",
        desc: "沉淀宿舍续住、搬家、账单、水电网络和生活服务高频处理方案。",
        to: "/international/abroad-life/ListPage",
        icon: <EnvironmentOutlinedIcon />,
        badgeLabel: "Housing",
        footerLabel: "住宿与生活",
      },
      {
        key: "abroad-visa",
        title: "签证续办与材料更新",
        desc: "追踪续签时间、证明文件、学校支持函和线上预约进度。",
        to: "/international/process-flow",
        icon: <RocketOutlinedIcon />,
        badgeLabel: "Visa",
        footerLabel: "身份与材料",
      },
      {
        key: "abroad-emergency",
        title: "紧急事务与联系人",
        desc: "把医疗、报警、证件遗失、回国变更等紧急事务整理成速查卡。",
        to: "/international/cultural-training",
        icon: <SafetyOutlinedIcon />,
        badgeLabel: "Emergency",
        footerLabel: "应急支持",
      },
    ],
  }),
  entry({
    key: "international-return-service",
    title: "回国与成果沉淀",
    shortLabel: "回国沉淀",
    desc: "提醒学分认定、成绩转换、报销归档，并沉淀交换经验与课程评价。",
    to: "/international/return-service",
    icon: <RollbackOutlinedIcon />,
    badgeLabel: "Return",
    footerLabel: "返校与经验库",
    subLinks: [
      { label: "返校事项", to: "/international/return-service/ListPage" },
      { label: "在外支持", to: "/international/abroad-life" },
      { label: "项目中心", to: "/international/exchange-hub" },
    ],
    landingHeadline: "回国与成果沉淀",
    landingSubtitle: "返校之后不是结束，而是把学分、材料、报销和经验沉淀成可复用资产的关键阶段。",
    landingFeatures: [
      {
        key: "return-credit",
        title: "学分认定与成绩转换",
        desc: "梳理返校后最先处理的成绩单、课程对应和学院认定事项。",
        to: "/international/return-service/ListPage",
        icon: <BankOutlinedIcon />,
        badgeLabel: "Credit",
        footerLabel: "学分与成绩",
      },
      {
        key: "return-reimburse",
        title: "报销办理与材料归档",
        desc: "统一整理发票、证明、扫描件和学校系统所需材料，减少二次补件。",
        to: "/international/return-service/ListPage",
        icon: <DeploymentUnitOutlinedIcon />,
        badgeLabel: "Archive",
        footerLabel: "报销与归档",
      },
      {
        key: "return-sharing",
        title: "经验分享与 FAQ 沉淀",
        desc: "把课程体验、城市建议、坑点和流程经验回流给后续学生。",
        to: "/international/return-service/ListPage",
        icon: <TranslationOutlinedIcon />,
        badgeLabel: "Sharing",
        footerLabel: "经验回流",
      },
      {
        key: "return-evaluation",
        title: "项目复盘与评价反馈",
        desc: "形成院校项目、课程质量和支持体系的复盘，反哺下一轮申请决策。",
        to: "/international/matching-lab",
        icon: <SearchOutlinedIcon />,
        badgeLabel: "Review",
        footerLabel: "复盘与评价",
      },
    ],
  }),
  entry({
    key: "international-welcome-portal",
    title: "来华留学生智能助手",
    shortLabel: "来华留学",
    desc: "面向 incoming students 提供签证、报到、住宿、校园办事、语言支持与适应建议。",
    to: "/international/welcome-portal",
    icon: <GlobalOutlinedIcon />,
    badgeLabel: "Incoming",
    footerLabel: "来华留学服务",
    subLinks: [
      { label: "报到支持", to: "/international/welcome-portal/ListPage" },
      { label: "邮件沟通", to: "/international/writing-desk" },
      { label: "文化适应", to: "/international/cultural-training" },
    ],
    landingHeadline: "来华留学生智能助手",
    landingSubtitle: "把来华前的签证、报到注册、住宿办理、校园办事和语言适应做成一站式支持面板。",
    landingFeatures: [
      {
        key: "incoming-visa",
        title: "签证与来华前材料",
        desc: "整理 JW 表、录取通知、体检、保险和入境前注意事项，支持双语沟通。",
        to: "/international/welcome-portal/ListPage",
        icon: <GlobalOutlinedIcon />,
        badgeLabel: "Visa",
        footerLabel: "来华前准备",
      },
      {
        key: "incoming-arrival",
        title: "报到注册与校园办理",
        desc: "覆盖报到、注册、校园卡、选课、宿舍入住和常见校务事项。",
        to: "/international/welcome-portal/ListPage",
        icon: <DeploymentUnitOutlinedIcon />,
        badgeLabel: "Arrival",
        footerLabel: "报到与注册",
      },
      {
        key: "incoming-language",
        title: "语言支持与日常适应",
        desc: "为中文沟通、课堂适应、生活服务和常见问题提供可复用模板与 FAQ。",
        to: "/international/writing-desk",
        icon: <TranslationOutlinedIcon />,
        badgeLabel: "Language",
        footerLabel: "语言与生活",
      },
      {
        key: "incoming-community",
        title: "住宿、社群与支持网络",
        desc: "沉淀宿舍、校园地图、就医、辅导员和国际处联系方式，帮助快速落地。",
        to: "/international/abroad-life",
        icon: <EnvironmentOutlinedIcon />,
        badgeLabel: "Community",
        footerLabel: "住宿与支持",
      },
    ],
  }),
];

export const internationalHubFeatures: Feature[] = internationalModuleCatalog.map(
  (item) => ({
    key: item.key,
    title: item.title,
    desc: item.desc,
    to: item.to,
    icon: item.icon,
    badgeLabel: item.badgeLabel,
    footerLabel: item.footerLabel,
    subLinks: item.subLinks,
  }),
);

export const internationalHomeSubLinks = internationalModuleCatalog.map((item) => ({
  label: item.shortLabel,
  to: item.to,
  icon: item.icon,
}));

export const getInternationalModuleCatalogEntry = (key: string) => {
  const matched = internationalModuleCatalog.find((item) => item.key === key);
  if (!matched) {
    throw new Error(`Unknown international module catalog key: ${key}`);
  }
  return matched;
};
