# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes for AICopilotService."""
import grpc
from app.rpc import ai_copilot_pb2 as ai__copilot__pb2


class AICopilotServiceStub(object):
    """Client stub for AICopilotService."""
    def __init__(self, channel):
        self.Complete = channel.unary_unary(
            '/ai_copilot.v1.AICopilotService/Complete',
            request_serializer=ai__copilot__pb2.CompleteRequest.SerializeToString,
            response_deserializer=ai__copilot__pb2.CompleteResponse.FromString,
        )


class AICopilotServiceServicer(object):
    """Server interface for AICopilotService."""
    def Complete(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AICopilotServiceServicer_to_server(servicer, server):
    from grpc import unary_unary_rpc_method_handler
    rpc_method_handlers = {
        'Complete': unary_unary_rpc_method_handler(
            servicer.Complete,
            request_deserializer=ai__copilot__pb2.CompleteRequest.FromString,
            response_serializer=ai__copilot__pb2.CompleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_service_handler('ai_copilot.v1.AICopilotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
