# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, '', 'ai-copilot/v1/ai-copilot.proto'
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1f\x61i-copilot/v1/ai-copilot.proto\x12\rai_copilot.v1'
    b'\"\x83\x01\n\x0f\x43ompleteRequest\x12\x1a\n\x08language\x18\x01 \x01(\tR\x08language'
    b'\x12!\n\x0c\x66ile_content\x18\x02 \x01(\tR\x0b\x66ileContent'
    b'\x12#\n\rcursor_offset\x18\x03 \x01(\x05R\x0c\x63ursorOffset'
    b'\x12\x1b\n\tfile_path\x18\x04 \x01(\tR\x08\x66ilePath'
    b'\"\x32\n\x10\x43ompleteResponse\x12\x1e\n\nsuggestion\x18\x01 \x01(\tR\nsuggestion'
    b'2[\n\x10\x41ICopilotService\x12G\n\x08\x43omplete'
    b'\x12\x1e.ai_copilot.v1.CompleteRequest'
    b'\x1a\x1f.ai_copilot.v1.CompleteResponse\"\x00'
    b'BSZQgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-copilot/v1;aicopilotv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_copilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'ZQgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-copilot/v1;aicopilotv1'
