# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai-copilot/v1/ai-copilot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai-copilot/v1/ai-copilot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61i-copilot/v1/ai-copilot.proto\x12\rai_copilot.v1\"c\n\x0f\x43ompleteRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\t\x12\x15\n\rcursor_offset\x18\x03 \x01(\x05\x12\x11\n\tfile_path\x18\x04 \x01(\t\"&\n\x10\x43ompleteResponse\x12\x12\n\nsuggestion\x18\x01 \x01(\t2_\n\x10\x41ICopilotService\x12K\n\x08\x43omplete\x12\x1e.ai_copilot.v1.CompleteRequest\x1a\x1f.ai_copilot.v1.CompleteResponseBQZOgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-copilot/v1;aicopilotv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_copilot.v1.ai_copilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZOgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-copilot/v1;aicopilotv1'
  _globals['_COMPLETEREQUEST']._serialized_start=49
  _globals['_COMPLETEREQUEST']._serialized_end=148
  _globals['_COMPLETERESPONSE']._serialized_start=150
  _globals['_COMPLETERESPONSE']._serialized_end=188
  _globals['_AICOPILOTSERVICE']._serialized_start=190
  _globals['_AICOPILOTSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
