syntax = "proto3";
package sandbox.v1;
option go_package = "github.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/sandbox/v1;sandboxv1";

service RunnerService {
  rpc RunCode(RunCodeRequest) returns (RunCodeResponse);
}

message RunCodeRequest {
  string language        = 1;
  string code            = 2;
  string stdin           = 3;
  int32  timeout_seconds = 4;
  repeated RunFile files = 5;
}

message RunFile {
  string path    = 1;
  string content = 2;
}

message RunCodeResponse {
  string stdout       = 1;
  string stderr       = 2;
  int32  exit_code    = 3;
  int64  execution_ms = 4;
  string error        = 5;
}
