// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ai-chat/v1/ai-chat.proto

package aichatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIChatService_Chat_FullMethodName   = "/ai_chat.v1.AIChatService/Chat"
	AIChatService_FixBug_FullMethodName = "/ai_chat.v1.AIChatService/FixBug"
)

// AIChatServiceClient is the client API for AIChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIChatServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	FixBug(ctx context.Context, in *FixBugRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FixBugResponse], error)
}

type aIChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIChatServiceClient(cc grpc.ClientConnInterface) AIChatServiceClient {
	return &aIChatServiceClient{cc}
}

func (c *aIChatServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIChatService_ServiceDesc.Streams[0], AIChatService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIChatService_ChatClient = grpc.ServerStreamingClient[ChatResponse]

func (c *aIChatServiceClient) FixBug(ctx context.Context, in *FixBugRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FixBugResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIChatService_ServiceDesc.Streams[1], AIChatService_FixBug_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FixBugRequest, FixBugResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIChatService_FixBugClient = grpc.ServerStreamingClient[FixBugResponse]

// AIChatServiceServer is the server API for AIChatService service.
// All implementations must embed UnimplementedAIChatServiceServer
// for forward compatibility.
type AIChatServiceServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	FixBug(*FixBugRequest, grpc.ServerStreamingServer[FixBugResponse]) error
	mustEmbedUnimplementedAIChatServiceServer()
}

// UnimplementedAIChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIChatServiceServer struct{}

func (UnimplementedAIChatServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAIChatServiceServer) FixBug(*FixBugRequest, grpc.ServerStreamingServer[FixBugResponse]) error {
	return status.Errorf(codes.Unimplemented, "method FixBug not implemented")
}
func (UnimplementedAIChatServiceServer) mustEmbedUnimplementedAIChatServiceServer() {}
func (UnimplementedAIChatServiceServer) testEmbeddedByValue()                       {}

// UnsafeAIChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIChatServiceServer will
// result in compilation errors.
type UnsafeAIChatServiceServer interface {
	mustEmbedUnimplementedAIChatServiceServer()
}

func RegisterAIChatServiceServer(s grpc.ServiceRegistrar, srv AIChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIChatService_ServiceDesc, srv)
}

func _AIChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIChatServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIChatService_ChatServer = grpc.ServerStreamingServer[ChatResponse]

func _AIChatService_FixBug_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FixBugRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIChatServiceServer).FixBug(m, &grpc.GenericServerStream[FixBugRequest, FixBugResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIChatService_FixBugServer = grpc.ServerStreamingServer[FixBugResponse]

// AIChatService_ServiceDesc is the grpc.ServiceDesc for AIChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_chat.v1.AIChatService",
	HandlerType: (*AIChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIChatService_Chat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FixBug",
			Handler:       _AIChatService_FixBug_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai-chat/v1/ai-chat.proto",
}
