// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: ai-chat/v1/ai-chat.proto

package aichatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant" | "system"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ai_chat_v1_ai_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	FileContext   string                 `protobuf:"bytes,2,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_chat_v1_ai_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetFileContext() string {
	if x != nil {
		return x.FileContext
	}
	return ""
}

func (x *ChatRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_chat_v1_ai_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type FixBugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixBugRequest) Reset() {
	*x = FixBugRequest{}
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixBugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixBugRequest) ProtoMessage() {}

func (x *FixBugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixBugRequest.ProtoReflect.Descriptor instead.
func (*FixBugRequest) Descriptor() ([]byte, []int) {
	return file_ai_chat_v1_ai_chat_proto_rawDescGZIP(), []int{3}
}

func (x *FixBugRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FixBugRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FixBugRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type FixBugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixBugResponse) Reset() {
	*x = FixBugResponse{}
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixBugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixBugResponse) ProtoMessage() {}

func (x *FixBugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_chat_v1_ai_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixBugResponse.ProtoReflect.Descriptor instead.
func (*FixBugResponse) Descriptor() ([]byte, []int) {
	return file_ai_chat_v1_ai_chat_proto_rawDescGZIP(), []int{4}
}

func (x *FixBugResponse) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *FixBugResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_ai_chat_v1_ai_chat_proto protoreflect.FileDescriptor

const file_ai_chat_v1_ai_chat_proto_rawDesc = "" +
	"\n" +
	"\x18ai-chat/v1/ai-chat.proto\x12\n" +
	"ai_chat.v1\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x81\x01\n" +
	"\vChatRequest\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.ai_chat.v1.ChatMessageR\bmessages\x12!\n" +
	"\ffile_context\x18\x02 \x01(\tR\vfileContext\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"8\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"d\n" +
	"\rFixBugRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\":\n" +
	"\x0eFixBugResponse\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done2\x8f\x01\n" +
	"\rAIChatService\x12;\n" +
	"\x04Chat\x12\x17.ai_chat.v1.ChatRequest\x1a\x18.ai_chat.v1.ChatResponse0\x01\x12A\n" +
	"\x06FixBug\x12\x19.ai_chat.v1.FixBugRequest\x1a\x1a.ai_chat.v1.FixBugResponse0\x01BKZIgithub.com/dieWehmut/nju-edu-ai-system/backend/pkg/pb/ai-chat/v1;aichatv1b\x06proto3"

var (
	file_ai_chat_v1_ai_chat_proto_rawDescOnce sync.Once
	file_ai_chat_v1_ai_chat_proto_rawDescData []byte
)

func file_ai_chat_v1_ai_chat_proto_rawDescGZIP() []byte {
	file_ai_chat_v1_ai_chat_proto_rawDescOnce.Do(func() {
		file_ai_chat_v1_ai_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_chat_v1_ai_chat_proto_rawDesc), len(file_ai_chat_v1_ai_chat_proto_rawDesc)))
	})
	return file_ai_chat_v1_ai_chat_proto_rawDescData
}

var file_ai_chat_v1_ai_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_chat_v1_ai_chat_proto_goTypes = []any{
	(*ChatMessage)(nil),    // 0: ai_chat.v1.ChatMessage
	(*ChatRequest)(nil),    // 1: ai_chat.v1.ChatRequest
	(*ChatResponse)(nil),   // 2: ai_chat.v1.ChatResponse
	(*FixBugRequest)(nil),  // 3: ai_chat.v1.FixBugRequest
	(*FixBugResponse)(nil), // 4: ai_chat.v1.FixBugResponse
}
var file_ai_chat_v1_ai_chat_proto_depIdxs = []int32{
	0, // 0: ai_chat.v1.ChatRequest.messages:type_name -> ai_chat.v1.ChatMessage
	1, // 1: ai_chat.v1.AIChatService.Chat:input_type -> ai_chat.v1.ChatRequest
	3, // 2: ai_chat.v1.AIChatService.FixBug:input_type -> ai_chat.v1.FixBugRequest
	2, // 3: ai_chat.v1.AIChatService.Chat:output_type -> ai_chat.v1.ChatResponse
	4, // 4: ai_chat.v1.AIChatService.FixBug:output_type -> ai_chat.v1.FixBugResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ai_chat_v1_ai_chat_proto_init() }
func file_ai_chat_v1_ai_chat_proto_init() {
	if File_ai_chat_v1_ai_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_chat_v1_ai_chat_proto_rawDesc), len(file_ai_chat_v1_ai_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_chat_v1_ai_chat_proto_goTypes,
		DependencyIndexes: file_ai_chat_v1_ai_chat_proto_depIdxs,
		MessageInfos:      file_ai_chat_v1_ai_chat_proto_msgTypes,
	}.Build()
	File_ai_chat_v1_ai_chat_proto = out.File
	file_ai_chat_v1_ai_chat_proto_goTypes = nil
	file_ai_chat_v1_ai_chat_proto_depIdxs = nil
}
