// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: ai-chat/v1/ai-chat.proto

package aichatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AIChatServiceClient is the client API for AIChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIChatServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (AIChatService_ChatClient, error)
	FixBug(ctx context.Context, in *FixBugRequest, opts ...grpc.CallOption) (AIChatService_FixBugClient, error)
}

type aIChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIChatServiceClient(cc grpc.ClientConnInterface) AIChatServiceClient {
	return &aIChatServiceClient{cc}
}

func (c *aIChatServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (AIChatService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIChatService_ServiceDesc.Streams[0], "/ai_chat.v1.AIChatService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &aIChatServiceChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIChatService_ChatClient interface {
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type aIChatServiceChatClient struct {
	grpc.ClientStream
}

func (x *aIChatServiceChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aIChatServiceClient) FixBug(ctx context.Context, in *FixBugRequest, opts ...grpc.CallOption) (AIChatService_FixBugClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIChatService_ServiceDesc.Streams[1], "/ai_chat.v1.AIChatService/FixBug", opts...)
	if err != nil {
		return nil, err
	}
	x := &aIChatServiceFixBugClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIChatService_FixBugClient interface {
	Recv() (*FixBugResponse, error)
	grpc.ClientStream
}

type aIChatServiceFixBugClient struct {
	grpc.ClientStream
}

func (x *aIChatServiceFixBugClient) Recv() (*FixBugResponse, error) {
	m := new(FixBugResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AIChatServiceServer is the server API for AIChatService service.
// All implementations must embed UnimplementedAIChatServiceServer
// for forward compatibility
type AIChatServiceServer interface {
	Chat(*ChatRequest, AIChatService_ChatServer) error
	FixBug(*FixBugRequest, AIChatService_FixBugServer) error
	mustEmbedUnimplementedAIChatServiceServer()
}

// UnimplementedAIChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIChatServiceServer struct {
}

func (UnimplementedAIChatServiceServer) Chat(*ChatRequest, AIChatService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAIChatServiceServer) FixBug(*FixBugRequest, AIChatService_FixBugServer) error {
	return status.Errorf(codes.Unimplemented, "method FixBug not implemented")
}
func (UnimplementedAIChatServiceServer) mustEmbedUnimplementedAIChatServiceServer() {}

// UnsafeAIChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIChatServiceServer will
// result in compilation errors.
type UnsafeAIChatServiceServer interface {
	mustEmbedUnimplementedAIChatServiceServer()
}

func RegisterAIChatServiceServer(s grpc.ServiceRegistrar, srv AIChatServiceServer) {
	s.RegisterService(&AIChatService_ServiceDesc, srv)
}

func _AIChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIChatServiceServer).Chat(m, &aIChatServiceChatServer{stream})
}

type AIChatService_ChatServer interface {
	Send(*ChatResponse) error
	grpc.ServerStream
}

type aIChatServiceChatServer struct {
	grpc.ServerStream
}

func (x *aIChatServiceChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AIChatService_FixBug_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FixBugRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIChatServiceServer).FixBug(m, &aIChatServiceFixBugServer{stream})
}

type AIChatService_FixBugServer interface {
	Send(*FixBugResponse) error
	grpc.ServerStream
}

type aIChatServiceFixBugServer struct {
	grpc.ServerStream
}

func (x *aIChatServiceFixBugServer) Send(m *FixBugResponse) error {
	return x.ServerStream.SendMsg(m)
}

// AIChatService_ServiceDesc is the grpc.ServiceDesc for AIChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_chat.v1.AIChatService",
	HandlerType: (*AIChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIChatService_Chat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FixBug",
			Handler:       _AIChatService_FixBug_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai-chat/v1/ai-chat.proto",
}
